name: atac_ebna2
pep_version: 2.0.0
sample_table: atac_ebna2_annotation.csv
subsample_table: null

looper:
  output_dir: atac_ebna2

sample_modifiers:
  append:
    pipeline_interfaces: ${HOME}/code/pepatac/pipeline_interface.yaml
    genome: hg38
    read1: FQ1
    read2: FQ2          
  derive:
    attributes: [read1, read2, SRR_files]
    sources:
      SRA: "${SRABAM}/{SRR}.bam"
      FQ1: "/home/nsheff/ncbi/public/sra/{SRR}_1.fastq.gz"
      FQ2: "/home/nsheff/ncbi/public/sra/{SRR}_2.fastq.gz"
project_modifiers:
  amend:
    sra_convert:
      sample_modifiers:
        append:
          SRR_files: SRA
          pipeline_interfaces: ${HOME}/code/geofetch/pipeline_interface_convert.yaml
        derive:
          attributes: [read1, read2, SRR_files]
          sources:
            SRA: "/home/nsheff/ncbi/public/sra/{SRR}.sra"
            FQ: "/home/nsheff/ncbi/public/sra/{SRR}.fastq.gz"
            FQ1: "/home/nsheff/ncbi/public/sra/{SRR}_1.fastq.gz"
            FQ2: "/home/nsheff/ncbi/public/sra/{SRR}_2.fastq.gz"

